name: calc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.15
  fluttertoast: 8.2.6
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  google_sign_in: ^6.2.0
  flutter_facebook_auth: 7.0.1
  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^2.5.0
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
